"""
exceptions.py
02 July 2022 01:33:55

Defines custom exceptions.
"""


class CommandError(Exception):
    pass
